template: true   # required for local templates
valuesFilePath: values.yml

resources:
  - name: demoRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.demoRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.demoRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps 
        include: master
  - name: demoBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    MyMavenIntegration
      buildName:            demoBuild
      buildNumber:          1

pipelines:
  - name: demoPipeline2 
    steps:
      - name: build_step2
        type: MvnBuild
        configuration:        
          autoPublishBuildInfo: true
          outputResources:
            - name: demoBuildInfo          
          inputResources:
            - name: demoRepo             # Use the demoRepo resource            
          environmentVariables:
              repo_username: "steven.randolph@realmethods.com"
              repo_passsword: "6969Cutlass!!"
              repo_url: "https://knowops.jfrog.io/artifactory/local-maven-repo"
          sourceLocation: .
          mvnCommand: compile
          integrations:
            - name: MyMavenIntegration    
          forceXrayScan: true
          failOnScan: true   
#          deployerReleaseRepo: local-maven-repo
#          deployerSnapshotRepo: local-maven-repo
        execution:
          onSuccess:
           - echo "Build step using Maven is complete!"     
