template: true   # required for local templates
valuesFilePath: values.yml

resources:
  - name: demoRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.demoRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.demoRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

pipelines:
  - name: demoPipeline
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
            - "8"
    steps:
      - name: build_step
        type: Bash
        configuration:
          inputResources:
            - name: demoRepo     # Trigger execution on code commit
          affinityGroup: together	  
        execution:
          onExecute:
            - sudo apt-get install -y maven
            - cd $res_src_resourcePath
            - mvn test
            - mkdir -p JFrog_Pipelines/testresults
            - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} JFrog_Pipelines/testresults/ \;
          onSuccess:
            - echo "Build step using Maven is complete!"     
