template: true   # required for local templates
valuesFilePath: values.yml

resources:
  - name: demoRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located 
      gitProvider: {{ .Values.demoRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.demoRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps  
        include: master
  - name: demoBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    MyMavenIntegration
      buildName:            demoBuild
      buildNumber:          1
  - name: demoDockerBuildInfo2
    type: BuildInfo
    configuration:
      sourceArtifactory:    MyDockerIntegration
      buildName:            demoDockerBuild
      buildNumber:          1
  - name: buildArchiveFile
    type: FileSpec
    configuration:
      sourceArtifactory: MyMavenIntegration
      pattern: local-maven-repo/**/**/demo*.jar
      target: target/
  - name: dbp_image6
    type: Image
    configuration:
      registry: MyDockerHubIntegration               # <-- replace with your artifactory integration
      sourceRepository: local-docker-repo           # <-- required if registry is Artifactory
      imageName: realmethods/myapp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: false
      
pipelines:
  - name: demoPipeline2 
    steps:
      - name: build_step2
        type: MvnBuild
        configuration:        
          affinityGroup:       demo_affinity_group
          autoPublishBuildInfo: true
          outputResources:
            - name: demoBuildInfo          
          inputResources:
            - name: demoRepo             # Use the demoRepo resource             
          environmentVariables:
              repo_username: "steven.randolph@realmethods.com"
              repo_passsword: "6969Cutlass!!"              
              repo_url: "https://jcenter.bintray.com"
              skipTests: "true"
          sourceLocation: .
          mvnCommand: clean package
          integrations:
            - name: MyMavenIntegration    
          forceXrayScan: true
          failOnScan: true   
          deployerReleaseRepo: local-maven-repo
          deployerSnapshotRepo: local-maven-repo
        execution:
          onSuccess:
           - echo "Build step using Maven is complete!"     

      - name: docker_build_step2
        type: DockerBuild
        configuration:
          #inherits from bash
          affinityGroup:       demo_affinity_group
          dockerFileLocation:  .
          dockerFileName:      Dockerfile
          dockerImageName:     registry.hub.docker/realmethods/myapp
          dockerImageTag:      latest
 
          integrations:
            - name:            MyDockerHubIntegration  # required
 
          inputResources:
            - name:             demoRepo         # required, git repository containing your Dockerfile
            - name:             buildArchiveFile # what was constructed during the build step

          inputSteps:
            - name:             build_step2
            
        execution:
          onStart:
            - echo "Preparing for Docker image build..."
          onSuccess:
            - echo "Docker image build was successful"
          onFailure:
            - echo "uh oh, something went wrong with the Docker image build"
            
      - name: docker_push_step
        type: DockerPush
        configuration:
          #inherits from bash
          affinityGroup:        demo_affinity_group
          targetRepository:     local-docker-repo   # required
          forceXrayScan:        true                # default false
          failOnScan:           false               # default true
          autoPublishBuildInfo: true                # default false
 
          integrations:
            - name:             MyDockerIntegration  # required
            
          inputSteps:
            - name:             docker_build_step2   # required
          outputResources:
            - name:             demoDockerBuildInfo2 # required if autoPublishBuildInfo is true
            - name:             dbp_image6
        execution:
          onStart:
            - echo "Preparing for Docker image push..."
          onSuccess:
            - echo "Docker image push was successful"
          onFailure:
            - echo "uh oh, something went wrong with the Docker image push"

